#!/bin/bash

[ $# -lt 1 ] && { echo "Usage: $0 <file.vhd>"; exit 1; }
if [ $EUID != 0 ]; then
    echo "This script requires root privileges."
    sudo "$0" "$@"
    exit $?
fi
[ -f "$1" ] || { echo "File not found: $1"; exit 1; }

# unmount and detach loop-device
LOOPDEV=$(losetup -j "$1" | awk -F: '{print $1}')
if [[ $LOOPDEV ]]; then
    [[ $(findmnt $LOOPDEV) ]] && umount $LOOPDEV
    losetup -d $LOOPDEV
fi
