#!/bin/bash

[ $# -lt 1 ] && { echo "Usage: sudo $0 <file.vhd> <format=ntfs>"; exit 1; }
if [ $EUID != 0 ]; then
    echo "This script requires root privileges."
    echo "Please enter your password: "
    sudo "$0" "$@"
    exit $?
fi
[ $# -lt 2 ] && FMT=ntfs || FMT=$2

# find available loop device and bind it to the VHD
LOOPDEV=$(losetup -f)
echo "VHD will be attached temporarily to loop-device: $LOOPDEV"
losetup $LOOPDEV ./test.vhd

# format device
mkfs -t $FMT $LOOPDEV 

# detach loop-device
losetup -d $LOOPDEV
