#!/bin/bash

[ $# -lt 2 ] && { echo "Usage: $0 <file.vhd> <size>"; exit 1; }

#dd if=/dev/zero of="$1" bs=1M count=$2

# makes it easier to specify sizes as 10M or 1.2G
touch "$1"
truncate -s $2 "$1"
du -h "$1"
