#!/bin/bash

[ $# -lt 1 ] && { echo "Usage: $0 <file.vhd>"; exit 1; }

# determine attached loop-device
LOOPDEV=$(losetup -j "$1" | awk -F: '{print $1}')
[[ $LOOPDEV ]] || { echo "VHD does not appear to be mounted ($1)."; exit 1; }
[[ $(findmnt $LOOPDEV) ]] || { echo "VHD is attached but not mounted ($1)."; exit 1; }

# define function for bold print
info() {
    echo -e "$(tput bold)$(tput setaf 2)$* $(tput sgr0)"
}
hrule() {
    info "/---------- ---------- ---------- ---------- ----------/"
}

# show info about the device (size, mount-options, active processes)
info "# Size info:"
df -h $LOOPDEV 
hrule

info "# Mount info:"
findmnt $LOOPDEV
hrule

info "# Process info:"
fuser -mv $LOOPDEV
hrule
